fields:
    site_name:
        label: Site name
        comment: The website name as it should appear on the front-end
        default: ReCAPTCHA
    gc7_flashy:
        label: GC7 Flashy
        type: colorpicker
        assetVar: 'gc7flashy'
